### ISSUE TITLE
Any plans to support setting shadow color/offset on android?

### ISSUE THREAD

**Issue by themronion** [sthewissen/Xamarin.Forms.PancakeView#119]
Hey, nice plugin! The only thing i noticed there is no support for custom offsets and shadow colors on android, unfortunately. Maybe u can get some inspiration from freshly created [Sharpnado.Shadows?](https://github.com/roubachof/Sharpnado.Shadows/tree/master/Shadows) I think this functionality will be very popular among us, xamarin developers. Also i have a question. As i've understood from the source code there will be no shadows under api level 21?

**Comment by sthewissen** [comment]
Hi there, yeah, for shadows Sharpnado is definitely the better go-to at this point in time. It uses a completely different technique of custom drawing them. I have no plans on implementing that amount of detail though. The approach in PancakeView uses the `Elevation` property, which isn't around before API 21, which is why that distinction is made.

**Comment by themronion** [comment]
Ok, thx for the answer!
