### ISSUE TITLE
Cannot access a disposed object.

### ISSUE THREAD

**Issue by viveklpu2011** [sthewissen/Xamarin.Forms.PancakeView#29]
Getting exception when using Pancake View in xamarin forms on below line in the Pancake View Android Renderer.

if (_normalBitmap == null || _normalBitmap.Height != height || _normalBitmap.Width != width)
{

}

Please look into this.

Thanks

**Comment by sthewissen** [comment]
If you have some sort of sample project that can be used to reproduce I'll gladly take a look at it.

**Comment by adrianknight89** [comment]
@sthewissen I'm getting a similar exception as well. This happens when I refresh a ListView with pull to refresh (Every cell in the list is using DataTemplate -> ViewCell -> PancakeView -> Grid -> Children)

`System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.Bitmap'.`

```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeAbstractInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Bitmap.get_Height ()
PancakeDrawable.Draw (Android.Graphics.Canvas canvas)
Drawable.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.124(intptr,intptr,intptr)
```

**Comment by adrianknight89** [comment]
Also, I think the base call needs to be inside the above if:

https://github.com/sthewissen/Xamarin.Forms.PancakeView/blob/e6c0e1a7c64429f85ffbbc6c2659dd42b649bbca/src/Xamarin.Forms.PancakeView.Multi/Platforms/Android/PancakeDrawable.cs#L214

If PancakeDrawable is already disposed, there is no need to call base dispose again. Not sure if this will fix the issue though.

**Comment by adrianknight89** [comment]
Not sure if `DrawBitmap` here disposes the original bitmap

https://github.com/sthewissen/Xamarin.Forms.PancakeView/blob/e6c0e1a7c64429f85ffbbc6c2659dd42b649bbca/src/Xamarin.Forms.PancakeView.Multi/Platforms/Android/PancakeDrawable.cs#L64

Maybe you should look into cloning the original bitmap: https://stackoverflow.com/a/23683075

I don't have a reproduction right now as my app is quite complex. All I know is the issue happens when I refresh the ListView :)

**Comment by sthewissen** [comment]
Is this on v1.1.8? In that version @shanranm redid a lot of the Android-related rendering stuff so it might already be solved in that.

**Comment by adrianknight89** [comment]
The issue happens on 1.1.8.
