### ISSUE TITLE
Add ability to draw partial borders

### ISSUE THREAD

**Issue by adrianknight89** [sthewissen/Xamarin.Forms.PancakeView#30]
Sometimes we do not need borders on all four corners of a view. I have at least one important case where I need to draw a top and bottom border only and leave the sides intact. Can this library be extended to include selectively drawing borders?

**Comment by sthewissen** [comment]
In the current implementation, this would probably only be possible for iOS, since the path to draw the border is constructed bit by bit there. I _think_ it would basically be leaving out bits to draw. However, for Android, that's not the case. It might be possible, but I'd have to look into it further.

**Comment by adrianknight89** [comment]
I've never used drawing APIs on Android, but perhaps it is possible to draw individual paths instead of adding a [rounded rect](https://github.com/sthewissen/Xamarin.Forms.PancakeView/blob/3c8f38b2f6e1d47f5f06a64465f969ff7fcb2642/src/Xamarin.Forms.PancakeView.Multi/Platforms/Android/PancakeViewRenderer.cs#L187)? https://developer.android.com/reference/android/graphics/Path
