### ISSUE TITLE
[Feature ]Draw complex Shapes

### ISSUE THREAD

**Issue by minaairsupport** [sthewissen/Xamarin.Forms.PancakeView#84]
could we draw a shape like this with Pancake 

![swoopdeloop](https://user-images.githubusercontent.com/33718103/78739409-7ed01000-7954-11ea-8689-a2dcbee5a88e.png)

**Comment by sthewissen** [comment]
This is currently not possible and probably will not be possible in the future either. PancakeView's main purpose is to be a container of other element, not a shape drawing library. There is shape support being built into Xamarin as outlined in this spec https://github.com/xamarin/Xamarin.Forms/issues/9178 which is why I will not be doing double work by adding it to PancakeView.
