### ISSUE TITLE
[Feature] Softer or harder shadow

### ISSUE THREAD

**Issue by Depechie** [sthewissen/Xamarin.Forms.PancakeView#86]
I needed a softer shadow... so had to change the Elevation and TranslationZ on Android and ShadowRadius and ShadowOpacity on iOS.

Any ideas on how to elevate that to some properties on the PancakeView itself? Maybe 1 value from 0 to 10 and that it will use a small scale to change the values on the platforms?

**Comment by sthewissen** [comment]
PancakeView already has its own Elevation property which directly translates to Android and mimics Android behavior on iOS. That might be what you need. Since shadows are so different cross platform it’s hard to abstract more away. I’d gladly expose all shadow properties of iOS on Forms but I think 90% of it wouldn’t translate to Droid :(

**Comment by Depechie** [comment]
The elevation prop was not helpful enough :/ but yeah this is a difficult one to fix for sure.
Maybe like XF itself expose a small set off platform specific properties would indeed be nice.

**Comment by sthewissen** [comment]
On iOS and UWP the following shadow related options exist:
- Color
- BlurRadius
- Offset
- Opacity
***
On Android we have:
- Elevation
- TranslationZ

***

The question is what is the cleanest option for PancakeView to support these? I could add simple properties for them meaning that they would cover iOS and UWP without problems. On Android, however, none of those properties would do anything. I could also go the "platform specifics" route and make them prefixed or attached properties per platform. Or maybe another approach altogether? 🤔

**Comment by sthewissen** [comment]
I've been thinking that the cleanest version of this is probably something like:

```
public class DropShadow
{
   public Color Color { get; set; }
   public int Offset { get; set; }
   public float BlurRadius { get; set; }
   public float Opacity { get; set; }
   public int Elevation { get; set; }
   public int TranslationZ { get; set; }
}
```

**Comment by Depechie** [comment]
Only thing with this is that a dev needs to know the inner workings so that only a few will have impact on iOS and others only on Android.

But for me personally, this looks ok :)

**Comment by sthewissen** [comment]
Yeah, guess we could make something like Intellisense at least suggest some of that through comments. Obviously documentation on here would also reflect it. Not sure if there's much else we can do about  it since it tries to abstract something that doesn't share a whole lot in common while still remaining fully functional 😂

**Comment by sthewissen** [comment]
Made a start on this. I have one weird little binding thing that I can't figure out yet though. I implemented it as I mentioned above with a `DropShadow` class that inherits from `BindableObject`. This is then bound to a new bindable `Shadow` property on `PancakeView`. However, when updating values on the DropShadow class in XAML through binding the re-drawing trigger never fires because the OnElementPropertyChanged for PancakeView doesn't see that a property in the DropShadow class changed. I must be missing something, but if you have any pointers I'll gladly take them :)

![image](https://user-images.githubusercontent.com/2419439/79671705-d5e3a980-81cc-11ea-91bb-d71612ca5662.png)

**Comment by sthewissen** [comment]
Implemented in 1.4.2.

**Comment by Redth** [comment]
@sthewissen is there a way to set the shadow from a xaml style?

For instance I'd like to be able to do something like this:

```
<Style x:Key="card" TargetType="yummy:PancakeView">
	<Setter Property="yummy:PancakeView.Shadow">
		<yummy:DropShadow BlurRadius="2" Opacity="0.2" />
	</Setter>
</Setter>
```

This fails at runtime with an invalid case somewhere in the ctor of pancake view.

**Comment by sthewissen** [comment]
@Redth What device/platform are you running this on. Just did a quick test on iOS simulator and it seems to be doing what it should as you wrote it (with the end tag being `Style`). I'll give Android a try in the morning as I'd need to dig the device up from somewhere.

**Comment by Redth** [comment]
@sthewissen it was iOS as well (simulatior)... Perhaps I did something wrong somewhere else in my code for it.  If it's working for you then great, I'll figure out why it isn't here :)

**Comment by themronion** [comment]
U can grab some insipration for implementing the needed properties for android from [here](https://github.com/roubachof/Sharpnado.Shadows/tree/master/Shadows)
